theme: jekyll-theme-slate

baseurl: "/notes"
title: Notas de aprendizajes
description: Notas tomadas durante mis experimentos y otras cosas

show_downloads: false
google_analytics:

excerpt_separator: <!-- more -->
